### ISSUE TITLE
Compile nginx use --with-pcre=objs/lib/pcre2 error

### ISSUE THREAD

**Issue by indiff** [PCRE2Project/pcre2#842]
the error <pre>
Finished searching libraries
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_get_hash_from_name8 referenced in function parse_regex
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_find_named_group8 referenced in function compile_branch
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_add_name_to_table8 referenced in function pcre2_compile_8
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_find_dupname_details8 referenced in function compile_branch
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_parse_scan_substr_args8 referenced in function compile_branch
pcre2-8.lib(pcre2_compile.obj) : error LNK2019: unresolved external symbol _pcre2_compile_parse_recurse_args8 referenced in function compile_branch
objs\nginx.exe : fatal error LNK1120: 6 unresolved externals
NMAKE : fatal error U1077: 'cl @C:\TEMP\nmAB39.tmp' : return code '0x2'
Stop.</pre>

**Comment by NWilson** [comment]
I'm sorry, there's not enough information here to diagnose. I don't know anything whatsoever about how nginx is built - you may be able to get more help asking your question to nginx users.

**Comment by AnYiEE** [comment]
I encountered the same issue. With all other conditions unchanged, it works fine with 10.46, but building fails with 10.47. (Unlike you, I'm building on Ubuntu.)

```
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether ln -s works... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether the -Werror option is usable... yes
checking for GCC compatible visibility declarations... yes
checking linker version script flag... --version-script
checking if version scripts can use complex wildcards... yes
checking for __attribute__((uninitialized))... yes
checking for __assume()... no
checking for __builtin_mul_overflow()... yes
checking for __builtin_unreachable()... yes
checking for assert.h... yes
checking for limits.h... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for dirent.h... yes
checking for windows.h... no
checking for sys/wait.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for memfd_create... yes
checking for mkostemp... yes
checking for secure_getenv... yes
checking for realpath... yes
checking for zlib.h... yes
checking for gzopen in -lz... yes
checking for bzlib.h... yes
checking for libbz2... yes
checking how to run the C preprocessor... cc -E
checking whether cc is Clang... no
checking whether pthreads work with "-pthread" and "-lpthread"... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether Intel CET is enabled... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libpcre2-8.pc
config.status: creating libpcre2-16.pc
config.status: creating libpcre2-32.pc
config.status: creating libpcre2-posix.pc
config.status: creating pcre2-config
config.status: creating src/pcre2.h
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing script-chmod commands
config.status: executing delete-old-chartables commands

pcre2-10.47 configuration summary:

    Install prefix ..................... : /usr/local
    C preprocessor ..................... : cc -E
    C compiler ......................... : cc
    Linker ............................. : /usr/bin/ld -m elf_x86_64
    C preprocessor flags ............... : 
    C compiler flags ................... : -pthread -O2 -fomit-frame-pointer -pipe  -fvisibility=hidden
    Linker flags ....................... : 
    Extra libraries .................... : -lpthread 

    Build 8-bit pcre2 library .......... : yes
    Build 16-bit pcre2 library ......... : no
    Build 32-bit pcre2 library ......... : no
    Include debugging code ............. : no
    Enable JIT compiling support ....... : yes
    Use SELinux allocator in JIT ....... : no
    Enable Unicode support ............. : yes
    Newline char/sequence .............. : lf
    \R matches only ANYCRLF ............ : no
    \C is disabled ..................... : no
    EBCDIC coding ...................... : no
    EBCDIC code for NL ................. : n/a
    EBCDIC coding ignoring compiler .... : no
    Rebuild char tables ................ : no
    Internal link size ................. : 2
    Maximum variable lookbehind ........ : 255
    Nested parentheses limit ........... : 250
    Heap limit ......................... : 20000000 kibibytes
    Match limit ........................ : 10000000
    Match depth limit .................. : MATCH_LIMIT
    Build shared libs .................. : no
        with symbol versioning ......... : yes
    Build static libs .................. : yes
    Enable JIT in pcre2grep ............ : yes
    Enable callouts in pcre2grep ....... : yes
    Enable fork in pcre2grep callouts .. : yes
    Initial buffer size for pcre2grep .. : 20480
    Maximum buffer size for pcre2grep .. : 1048576
    Link pcre2grep with libz ........... : no
    Link pcre2grep with libbz2 ......... : no
    Link pcre2test with libedit ........ : no
    Link pcre2test with libreadline .... : no
    Enable Valgrind support ............ : no
    Code coverage ...................... : no
    Fuzzer support ..................... : no
    Differential fuzzer support ........ : no
    Use %zu and %td .................... : auto

make: *** [Makefile:10：build] return code '0x2'
```

**Comment by MatthewVernon** [comment]
FWIW, as part of recent testing, we did rebuild Debian nginx-from-unstable against 10.47-from-experimental, and it worked OK - [debusine output](https://github.com/PCRE2Project/pcre2/issues/842#issuecomment-3483326019)

**Comment by NWilson** [comment]
Could you provide, or link to, instructions for how you are fetching, configuring, and building nginx?

If I had a blank Linux VM, what would I need to do to get to that build error you're seeing?

I tried the following - and it worked:

```sh
curl -L -O https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.gz
curl -L -O https://nginx.org/download/nginx-1.28.0.tar.gz
tar xzf pcre2-10.47.tar.gz
tar xzf nginx-1.28.0.tar.gz
cd nginx-1.28.0
./configure --with-pcre=`pwd`/../pcre2-10.47
make
```

**Comment by thierryba** [comment]
that is actually a problem in nginx, see https://github.com/nginx/nginx/pull/963

**Comment by AnYiEE** [comment]
My build command:

```
apt install build-essential git
cd /usr/src

wget https://nginx.org/download/nginx-1.28.0.tar.gz
tar -xzf nginx-1.28.0.tar.gz && rm nginx-1.28.0.tar.gz

wget https://github.com/quictls/openssl/archive/refs/tags/openssl-3.3.0-quic1.tar.gz
tar -xzf openssl-3.3.0-quic1.tar.gz && rm openssl-3.3.0-quic1.tar.gz

wget https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.gz
tar -xzf pcre2-10.47.tar.gz && rm pcre2-10.47.tar.gz

wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
tar -xzf zlib-1.3.1.tar.gz && rm zlib-1.3.1.tar.gz

git clone https://github.com/google/ngx_brotli
cd ngx_brotli && git submodule update --init --recursive && cd ..

git clone https://github.com/leev/ngx_http_geoip2_module
git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_module
git clone https://github.com/openresty/echo-nginx-module
git clone https://github.com/openresty/headers-more-nginx-module

cd nginx-1.28.0
./configure --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --lock-path=/var/lock/nginx.lock --modules-path=/usr/lib/nginx/modules --pid-path=/run/nginx.pid --sbin-path=/usr/sbin/nginx --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --with-compat --with-file-aio --with-pcre-jit --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module --with-mail --with-mail_ssl_module --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_http_geoip2_module --add-dynamic-module=../ngx_http_substitutions_filter_module --add-dynamic-module=../echo-nginx-module --add-dynamic-module=../headers-more-nginx-module --with-openssl=../openssl-openssl-3.3.0-quic1 --with-pcre=../pcre2-10.47 --with-zlib=../zlib-1.3.1 --with-http_v3_module --with-cc-opt=-I../openssl-openssl-3.3.0-quic1/build/include --with-ld-opt=-L../openssl-openssl-3.3.0-quic1/build/lib
make -j8
```

If it's a new environment, it might prompt that some dependency libraries are missing, but they can all be installed through `apt install`. I'm sorry I added too many modules, but they were fine before. I hope this information is helpful.

My current `nginx -V` output

```
root@localhost:/usr/src# nginx -V
nginx version: nginx/1.28.0
built by gcc 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04) 
built with OpenSSL 3.3.0+quic 30 Jan 2024
TLS SNI support enabled
configure arguments: same as above, except --with-pcre=../pcre2-10.46
```

**Comment by NWilson** [comment]
@AnYiEE I still couldn't reproduce your build failure on Ubuntu (24.04 LTS). I had to install a few extra packages (libxslt1-dev, maxminddb-dev, and so on), and then, I ran your script. Compilation succeeded.

When you received the message `make: *** [Makefile:10：build] return code '0x2'` was there not any further output?

You can run `make -d` to get even more verbose output. There should be an indication of which file failed to compile or link.

**Comment by AnYiEE** [comment]
Thanks to @NWilson, I added `-d` and saw the detailed logs, then re-downloaded quictls, and now it can be successfully built. Sorry for the trouble. Also hope that indiff can find a suitable solution.

**Comment by NWilson** [comment]
Thank you for reporting back.

The issue from @AnYiEE (on Ubuntu) has been fixed by re-downloading quictls. Not a PCRE2 bug.

The issue from @indiff has been diagnosed by @thierryba in the linked issue https://github.com/nginx/nginx/pull/963. Not a PCRE2 bug: nginx on Windows builds PCRE2 using its own Makefile (nginx on Unix uses PCRE2's configure & make). The nginx Windows makefile has a hardcoded list of filenames, so cannot be used with PCRE2 10.47 yet. In any case, nginx on Windows is a semi-supported beta/preview platform, and has poor performance. Not a major use-case anyway. (You'd be better off using Docker on Windows to run the Linux nginx in a container. It would be faster and better-supported.)
